### ISSUE TITLE
如何实现用fn+f4/f5亮度调节

### ISSUE THREAD

**Issue by audtc** [jasper-wan/Xiaomi-Air-i5-7200U#1]
你好，我型号和你完全一样，想知道实现fn快捷键亮度调节的具体方法。谢谢！

**Comment by jasper-wan** [comment]
@audtc 10.14.3的时候这个EFI的亮度控制还是正常的，config里面的两个PATCH（Q1C和Q1D）就是这个作用。但是升级到10.14.5之后就失效了，你可以参考https://www.insanelymac.com/forum/topic/305030-guide-how-to-fix-brightness-hotkeys-in-dsdt/这个帖子，我尝试过没有效果

**Comment by audtc** [comment]
我用你的efi在10.14.5里面是可以用fn+f4/5调节亮度的，并没有你说的失效

**Comment by jasper-wan** [comment]
那就很神奇了，我自己用的一直没法控制

发自 Windows 10 版邮件应用

在 2019年7月2日，11:22，audtc <notifications@github.com<mailto:notifications@github.com>> 写道：


我用你的efi在10.14.5里面是可以用fn+f4/5调节亮度的，并没有你说的失效
