### ISSUE TITLE
10.15.1 19B88 USB端口问题

### ISSUE THREAD

**Issue by vip212** [jasper-wan/Xiaomi-Air-i5-7200U#10]
10.15.1 19B88 USB端口问题
笔记本右边的USB口连接USB2.0的设备无反应，比如我插入鼠标，鼠标的灯是不会亮的，但插入USB3.0的U盘又能显示！
我自已定制了端口也不行，不知为什么。右边的USB端口识别不了鼠标！

**Comment by jasper-wan** [comment]
你更新到最新到配置试试，我试了两个无线鼠标都没有问题。最新配置修复了一个USB的问题。

**Comment by vip212** [comment]
更新最新的配置了，可能是我的电脑不一样吧

**Comment by vip212** [comment]
现在一切都没问题了！正常了，一切正常,谢谢大师的分享
