### ISSUE TITLE
10.14.5出现息屏断网现象，有什么好的解决方案吗

### ISSUE THREAD

**Issue by Dom-page** [jasper-wan/Xiaomi-Air-i5-7200U#12]
我用的是网线，在网上找的教程都没用

**Comment by jasper-wan** [comment]
打开电能小憩，禁止休眠试试

**Comment by Dom-page** [comment]
> ：电小憩，禁止休眠试试

![image](https://user-images.githubusercontent.com/49628315/70601669-8d6c1c00-1c2d-11ea-8024-a605c6bd72fe.png)
感谢回复，一直都是这样设置，插着电用，还是不行

**Comment by rootwhois** [comment]
我也是会，希望大神能够解决一下

**Comment by jasper-wan** [comment]
合并入 #22
