### ISSUE TITLE
[建议]已经有intel的蓝牙驱动了，建议整合一下

### ISSUE THREAD

**Issue by tg567** [jasper-wan/Xiaomi-Air-i5-7200U#15]
https://github.com/zxystd/IntelBluetoothFirmware
已经有intel的蓝牙驱动了，我自己加进去可以使用，可能存在一些小问题，正常连接音箱，键盘这些没有多大的问题，建议整合进去

**Comment by vip212** [comment]
等大师更新，这个大好了，感谢楼上提供！

**Comment by rootwhois** [comment]
同等

**Comment by rootwhois** [comment]
我用了蓝牙驱动，但是打开蓝牙的设置面板会卡，你是否有相同的情况呢

**Comment by tg567** [comment]
> 我用了蓝牙驱动，但是打开蓝牙的设置面板会卡，你是否有相同的情况呢

没有，我是正常的

**Comment by BlackJocker1995** [comment]
基于10.14.6编译的版本，目前能使用。


[https://github.com/zxystd/IntelBluetoothFirmware/files/4018076/IntelBluetoothFirmware.kext.10.14.zip](kext)

**Comment by xiaoheiba** [comment]
链接鼠标不能用

**Comment by jasper-wan** [comment]
合并入 #22
