### ISSUE TITLE
感觉更新15.4存在兼容问题

### ISSUE THREAD

**Issue by rootwhois** [jasper-wan/Xiaomi-Air-i5-7200U#20]
当前的efi可以直接升级15.3
但是直接升级15.4重启之后的果标跑一阵会假死，短按电源键重新开机后，出现的升级错误如下：

![img](https://tva1.sinaimg.cn/large/00831rSTgy1gd8v7xfx5qj30u01qs1kx.jpg)

**Comment by Android-AwesomeRoy** [comment]
你这个卡+号, log 里面写了 "CFG没解锁", 你看看 BIOS 里面, 关于 CPU 相关的选项能不能把 CFG 设置为 unlock

**Comment by rootwhois** [comment]
> 你这个卡+号, log 里面写了 "CFG没解锁", 你看看 BIOS 里面, 关于 CPU 相关的选项能不能把 CFG 设置为 unlock

你好，我的bios里面没有这个选项，应该怎么办呀。

**Comment by cnbinwang** [comment]
所以你更新成功了吗？

**Comment by rootwhois** [comment]
> 你这个卡+号, log 里面写了 "CFG没解锁", 你看看 BIOS 里面, 关于 CPU 相关的选项能不能把 CFG 设置为 unlock

还是不行

**Comment by rootwhois** [comment]
> 所以你更新成功了吗？

失败了，你也试试吧，看看是不是只有我会

**Comment by cnbinwang** [comment]
不急不急，等大佬更新叭~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rootwhois"<notifications@github.com&gt;; 
发送时间: 2020年3月29日(星期天) 晚上9:32
收件人: "jasper-wan/Xiaomi-Air-i5-7200U"<Xiaomi-Air-i5-7200U@noreply.github.com&gt;; 
抄送: "Virtus.Pro"<1677784723@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [jasper-wan/Xiaomi-Air-i5-7200U] 感觉更新15.4存在兼容问题 (#20)





  
所以你更新成功了吗？
  
失败了，你也试试吧，看看是不是只有我会

**Comment by jasper-wan** [comment]
我笔记本还在学校里，现在还不能回去。

有条件请尝试下：
1. 关闭VT-d
2. 升级WhateverGreen和Lilu

**Comment by rootwhois** [comment]
> 我笔记本还在学校里，现在还不能回去。
> 
> 有条件请尝试下：
> 
> 1. 关闭VT-d
> 2. 升级WhateverGreen和Lilu

还是乖乖等大佬更新吧，我自己折腾导致差点clover更新不了。
我pull request了一个版本，加了英特尔内置蓝牙驱动，亲测可用。

**Comment by jasper-wan** [comment]
各位谁能帮忙提取一份小米笔记本的原版DSDT文件（Clover界面按F4，进macOS之后挂载EFI分区，位于EFI/CLOVER/ACPI/origin/下面），顺带标一下笔记本的BIOS版本
最近在家把家里的破笔记本给弄成黑苹果了，无奈小米本没带回家，只能先看看DSDT，希望各位能帮个忙

**Comment by tg567** [comment]
> 各位谁能帮忙提取一份小米笔记本的原版DSDT文件（Clover界面按F4，进macOS之后挂载EFI分区，位于EFI/CLOVER/ACPI/origin/下面），顺带标一下笔记本的BIOS版本
> 最近在家把家里的破笔记本给弄成黑苹果了，无奈小米本没带回家，只能先看看DSDT，希望各位能帮个忙

在Clover界面按F4卡死了，电源键才能关机重启，再去EFI/CLOVER/ACPI/下查看生成了origin目录，这样生成的可以用不，可以用的话今天晚上我回去上传一份

**Comment by jasper-wan** [comment]
> > 各位谁能帮忙提取一份小米笔记本的原版DSDT文件（Clover界面按F4，进macOS之后挂载EFI分区，位于EFI/CLOVER/ACPI/origin/下面），顺带标一下笔记本的BIOS版本
> > 最近在家把家里的破笔记本给弄成黑苹果了，无奈小米本没带回家，只能先看看DSDT，希望各位能帮个忙
> 
> 在Clover界面按F4卡死了，电源键才能关机重启，再去EFI/CLOVER/ACPI/下查看生成了origin目录，这样生成的可以用不，可以用的话今天晚上我回去上传一份

可以传上来我看下能不能用。按理说不应该卡死，尝试把原来的origin删除了再试试？或者更新一下clover版本

**Comment by tg567** [comment]
> > > 各位谁能帮忙提取一份小米笔记本的原版DSDT文件（Clover界面按F4，进macOS之后挂载EFI分区，位于EFI/CLOVER/ACPI/origin/下面），顺带标一下笔记本的BIOS版本
> > > 最近在家把家里的破笔记本给弄成黑苹果了，无奈小米本没带回家，只能先看看DSDT，希望各位能帮个忙
> > 
> > 
> > 在Clover界面按F4卡死了，电源键才能关机重启，再去EFI/CLOVER/ACPI/下查看生成了origin目录，这样生成的可以用不，可以用的话今天晚上我回去上传一份
> 
> 可以传上来我看下能不能用。按理说不应该卡死，尝试把原来的origin删除了再试试？或者更新一下clover版本

[origin.zip](https://github.com/jasper-wan/Xiaomi-Air-i5-7200U/files/4643963/origin.zip)
BIOS Version:XMAKB3M0P0304
EC Version:XMAKB3M0P04

**Comment by jasper-wan** [comment]
合并入 #22
