### ISSUE TITLE
OpenCore 迁移计划

### ISSUE THREAD

**Issue by jasper-wan** [jasper-wan/Xiaomi-Air-i5-7200U#22]
### 第一阶段：弄清楚各个文件/驱动的作用

已经弄清楚的显示为已勾选。功能还不清楚、有地方需要验证的，显示为未勾选。

ACPI补丁和ACPI重命名部分：

- [x] 没有DSDT.aml文件，没有做修改所以不需要
- [x] SSDT-ALS0：一个虚拟的光线传感器，用于关机时保存屏幕亮度信息
- [x] SSDT-DDGPU：禁用独立显卡
- [x] SSDT-DMAC：不清楚
- [x] SSDT-EC：仿冒的EC设备
- [x] SSDT-GPRW：修复睡眠后即时唤醒的bug
- [x] SSDT-HDAU：和声卡有关，不需要，可以删除
- [x] SSDT-HDEF：应该和HDAU一样，可以删除
- [x] SSDT-KBD0：亮度快捷键
- [x] SSDT-MATH：不清楚
- [x] SSDT-MEM2：不清楚
- [x] SSDT-PCIList：PCI设备列表定制，但是不清楚具体功能
- [x] SSDT-PMCR：不清楚
- [x] SSDT-PNLF：增加PNLF设备，和亮度调节有关
- [x] SSDT-PTSWAK：不清楚
- [x] SSDT-RMCF：这是RehabMan的SSDT补丁的配置文件，修改了其他SSDT之后这个文件可以移除掉
- [x] SSDT-RMNE：应该是和NullEthernet配合使用。AppleMusic通过检测这个网卡的MAC地址来判断机器。通过定制此文件中的MAC地址可以正常使用AppleMusic。待验证
- [x] SSDT-SATA：不清楚
- [x] SSDT-USB：USB端口定制
- [x] SSDT-XOSI：和_OSI重命名配合实现操作系统仿冒

SSDT重命名补丁：

- [x] 重命名_Q1D和_Q1C，显然是亮度快捷键的功能。如果要支持OpenCore，那么上面的KBD0补丁要加上_OSI判断
- [x] MATH to XATH，不清楚
- [x] _DSM to XDSM，不清楚功能，但是这个重命名范围很大，非常危险，应该移除掉
- [x] _OSI to XOSI，和上面的XOSI补丁配合使用的
- [x] EC0 to EC，实际上没用，应该删除
- [x] GFX0 to IGPU，被WG处理了，可以删除
- [x] HECI to IMEI，同样被WG处理了，可以删除
- [x] SAT0 to SATA，实际上没用，和SATA补丁配合使用，可以删除
- [x] Method(_PTS,1,N) to ZPTS，不清楚
- [x] Method(_WAK,1,S) to ZWAK，不清楚
- [x] Method(XWAK,0,N) to ZWAK，不清楚
- [x] Method(GPRW,2,N) to XPRW，配合SSDT-GPRW修复睡眠后即时唤醒bug

UEFI驱动部分：

已完成。注意ScanPolicy选项和增加HFSPlus.efi驱动

kexts驱动部分：

- [x] AppleALC：声卡支持
- [x] AppleBacklightInjecter：背光功能支持，还不清楚原理
- [x] CPUFriend和CPUFriendDataProvider：变频支持，但是DataProvider从哪里生成的还不清楚
- [x] CodecCommander：似乎已经被合并入AppleALC，可以删除，待验证
- [x] HibernationFixup：用途还不清楚
- [x] Lilu：其他多个驱动的依赖
- [x] NoTouchID：去除TouchID检测。移除它会导致系统在需要root权限时暂时卡顿
- [x] NullEthernet：增加一个内置的虚拟网卡
- [x] RtWlanU和RtWlanU1827：RTL的USB无线网卡驱动
- [x] USBInjectAll：注入USB端口方便后续定制。定制完之后应该可以去除掉。待验证
- [x] VirtualSMC：SMC功能模拟
- [x] VoodooI2C：触摸板支持，具体怎么和ACPI补丁配合还不清楚
- [x] VoodooI2CHID：触摸板支持，同上
- [x] VoodooPS2Controller：应该是键盘支持
- [x] WhateverGreen：集成显卡驱动

### 第二阶段：OpenCore的配置

已完成

### 第三阶段：Windows下各个ACPI补丁的兼容性测试

已完成

### 第四阶段：功能完善

已完成

## 需要支持的功能点

- [x] 集成显卡：显存识别，支持HDMI、DP外接
- [ ] DP外接的4k60Hz输出。可参考：<https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/117>
- [x] CPU变频
- [x] 触摸板：多指手势
- [x] 键盘：CapsLock键用于切换输入法时能正常使用
- [x] USB定制，可同时插入多个USB3.0设备；插入iPad支持充电
- [x] 息屏断网问题和电能小憩
- [x] 蓝牙，参考<https://github.com/zxystd/IntelBluetoothFirmware>
- [x] 睡眠唤醒
- [x] 声卡：音频输出、麦克风
- [x] 睡眠唤醒后的声音输出
- [x] 内置摄像头
- [x] 屏蔽独立显卡
- [x] 电池电量显示
- [x] 电池：解决提示更换电池的问题
- [x] 屏幕亮度调节滑块、亮度调节快捷键；背光信息在关机后可以保存
- [x] 苹果服务正常使用。主要是Apple Music
- [x] 支持macOS Big Sur

**Comment by cnbinwang** [comment]
大佬牛逼

**Comment by etotakeo** [comment]
等着大佬最新的~

**Comment by zenghongqiang** [comment]
大佬牛逼 现在用着Cheers0606这位大佬的OC 8代的efi 我的air13.3是7代的 https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI

**Comment by cnbinwang** [comment]
听说intel WiFi可以用了

**Comment by cnbinwang** [comment]
听说intel WiFi可以用了

**Comment by cnbinwang** [comment]
我已经用上intel WiFi驱动了，非常不错！！！！
[itlwm.kext.zip](https://github.com/jasper-wan/Xiaomi-Air-i5-7200U/files/4728122/itlwm.kext.zip)

**Comment by cnbinwang** [comment]
需要修改wifi 的ssid和密码

**Comment by cnbinwang** [comment]
听说有人在搞gui，等搞好了就完美了

**Comment by xiaoheiba** [comment]
有转移成功的吗

**Comment by xiaoheiba** [comment]
> 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI

8代的EFI在7代上能用吗

**Comment by etotakeo** [comment]
> > 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI
> 
> 8代的EFI在7代上能用吗

我的也是7代的，还有就是OC怎么装？我看了一下网上的，越看越糊涂。

**Comment by xiaoheiba** [comment]
> > > 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI
> > 
> > 
> > 8代的EFI在7代上能用吗
> 
> 我的也是7代的，还有就是OC怎么在选择启动项的时候能选择windows和deepin？我看了一下网上的，越看越糊涂。

你的oc制作成功了吗？

**Comment by zenghongqiang** [comment]
> > 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI
> 
> 8代的EFI在7代上能用吗

能用

**Comment by xiaoheiba** [comment]
> > > 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI
> > 
> > 
> > 8代的EFI在7代上能用吗
> 
> 能用

直接搬来 就能用？

**Comment by xiaoheiba** [comment]
> > > > 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI
> 
> > > 
> 
> > > 
> 
> > > 8代的EFI在7代上能用吗
> 
> > 
> 
> > 能用
> 
> 
> 
> 直接搬来 就能用？

需要修改什么参数吗

**Comment by zenghongqiang** [comment]
从clover迁移到oc ，直接用 没修改

**Comment by zenghongqiang** [comment]
> > > > > 大佬牛逼现在用着Cheers0606这个大佬的OC 8代的efi我的air13.3是7代的https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 8代的EFI在7代上能用吗
> > 
> > 
> > > 
> > 
> > 
> > > 能用
> > 
> > 
> > 直接搬来 就能用？
> 
> 需要修改什么参数吗

从clover迁移到oc ，直接用 没修改

**Comment by jasper-wan** [comment]
各位久等了，我捣鼓了两天，重启了无数次，终于更新到Big Sur了，OpenCore引导

<img width="1366" alt="screen" src="https://user-images.githubusercontent.com/15362491/90132937-39f43400-dda1-11ea-83d1-5761b85e09e0.png">

这一份EFI安装10.15.6也是没有问题的。

文件还需要再整理一下，预计本周内放出更新

**Comment by cnbinwang** [comment]
可

**Comment by jasper-wan** [comment]
已经发布，各位有兴趣的可以试一试。讨论群：533801737

**Comment by etotakeo** [comment]
大佬的wifi什么的都搞定了呀？

**Comment by jasper-wan** [comment]
> 大佬的wifi什么的都搞定了呀？

搞定了，用的[itlwm](https://github.com/OpenIntelWireless/itlwm)

**Comment by jasper-wan** [comment]
以上除4k支持以外都已完成（触摸板、蓝牙、Wi-Fi等均工作正常），我本地没有办法测试4k，各位谁有4k显示器的可以群里联系我帮忙调试，群号533801737

此帖终结，还请各位多多反馈/建议

**Comment by xiaoheiba** [comment]
网络很是不稳定
