### ISSUE TITLE
睡眠状态唤醒，没有声音了

### ISSUE THREAD

**Issue by chanbaihai** [jasper-wan/Xiaomi-Air-i5-7200U#24]
15.3 从睡眠状态唤醒电脑扬声器没有声音了，只能戴耳机，需要重启

**Comment by xiaoheiba** [comment]
> 了

**Comment by xiaoheiba** [comment]
> 15.3从睡眠状态唤醒电脑扬声器没有声音了，只能戴耳机，需要重启

更新驱动

**Comment by chanbaihai** [comment]
新驱动在哪儿下载？我是前几天直接下的你的EFI

**Comment by chanbaihai** [comment]
> > 15.3从睡眠状态唤醒电脑扬声器没有声音了，只能戴耳机，需要重启
> 
> 更新驱动

驱动从哪儿下载？

**Comment by xiaoheiba** [comment]
Kext-Updater

**Comment by chanbaihai** [comment]
> Kext-Updater

谢谢啊，我下载个试试，新手，刚装黑苹果，感谢！

**Comment by chanbaihai** [comment]
> Kext-Updater

我更新 APPALC 直接声卡就用不了了，更新哪个驱动？

**Comment by xiaoheiba** [comment]
> > Kext-Updater
> 
> 
> 
> 我更新 APPALC 直接声卡就用不了了，更新哪个驱动？

看看你的声卡注入的id

**Comment by chanbaihai** [comment]
> > > Kext-Updater
> > 
> > 
> > 我更新 APPALC 直接声卡就用不了了，更新哪个驱动？
> 
> 看看你的声卡注入的id

注入id就是这个项目的注入id 30没改  后来我改成99睡眠后也无法唤醒声卡，我试了另外一个EFI睡眠唤醒声卡是好的，但对照修改plist没用 [https://github.com/johnnync13/Xiaomi-Mi-Air](xiaomiEFI)，但这个efi触摸板不能用，所以没用这个，你能看下什么原因么？

**Comment by xiaoheiba** [comment]
> > > > Kext更新器
> > > 
> > > 
> > > 我更新APPALC直接声卡就用不了了，更新哪个驱动？
> > 
> > 
> > 看看你的声卡注入的id
> 
> 注入id就是这个项目的注入id 30没改后来我改成99睡眠后也无法唤醒声卡，我试了另外一个EFI睡眠唤醒声卡是好的，但对照修改plist没用[https://github.com/ johnnync13 / Xiaomi-Mi-Air](https://github.com/johnnync13/Xiaomi-Mi-Air)，但这个efi触摸板不能用，所以没用这个，你能看下什么原因么？

18款？

**Comment by chanbaihai** [comment]
> > > > > Kext更新器
> 
> > > > 
> 
> > > > 
> 
> > > > 我更新APPALC直接声卡就用不了了，更新哪个驱动？
> 
> > > 
> 
> > > 
> 
> > > 看看你的声卡注入的id
> 
> > 
> 
> > 注入id就是这个项目的注入id 30没改后来我改成99睡眠后也无法唤醒声卡，我试了另外一个EFI睡眠唤醒声卡是好的，但对照修改plist没用[https://github.com/ johnnync13 / Xiaomi-Mi-Air](https://github.com/johnnync13/Xiaomi-Mi-Air)，但这个efi触摸板不能用，所以没用这个，你能看下什么原因么？
> 
> 
> 
> 18款？

处理器是i5 7代的应该是17款

**Comment by xiaoheiba** [comment]
> > > > > > Kext更新器
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > 我更新APPALC直接声卡就用不了了，更新哪个驱动？
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 看看你的声卡注入的id
> > 
> > 
> > > 
> > 
> > 
> > > 注入id就是这个项目的注入id 30没改后来我改成99睡眠后也无法唤醒声卡，我试了另外一个EFI睡眠唤醒声卡是好的，但对照修改plist没用[https://github.com/ johnnync13 / Xiaomi-Mi-Air](https://github.com/johnnync13/Xiaomi-Mi-Air)，但这个efi触摸板不能用，所以没用这个，你能看下什么原因么？
> > 
> > 
> > 18款？
> 
> 处理器是i5 7代的应该是17款
https://github.com/jasper-wan/Xiaomi-Air-i5-7200U

**Comment by chanbaihai** [comment]
> > > > > > > Kext更新器
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > > > 我更新APPALC直接声卡就用不了了，更新哪个驱动？
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 看看你的声卡注入的id
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 注入id就是这个项目的注入id 30没改后来我改成99睡眠后也无法唤醒声卡，我试了另外一个EFI睡眠唤醒声卡是好的，但对照修改plist没用[https://github.com/ johnnync13 / Xiaomi-Mi-Air](https://github.com/johnnync13/Xiaomi-Mi-Air)，但这个efi触摸板不能用，所以没用这个，你能看下什么原因么？
> > > 
> > > 
> > > 18款？
> > 
> > 
> > 处理器是i5 7代的应该是17款
> > https://github.com/jasper-wan/Xiaomi-Air-i5-7200U

我用的就是这个EFI遇到睡眠无声音的问题，不过影响不大，解决不了就算了
