### ISSUE TITLE
外接4k显示器，识别成2k，无法选择4k，HDMI和type-c口都一样

### ISSUE THREAD

**Issue by chanbaihai** [jasper-wan/Xiaomi-Air-i5-7200U#25]
外接4k显示器，识别成2k，无法选择4k，HDMI和type-c口都一样
系统信息
Intel HD Graphics 620:

  Chipset Model:	Intel HD Graphics 620
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x5916
  Revision ID:	0x0002
  Metal:	Supported, feature set macOS GPUFamily2 v1
  Displays:
LG HDR 4K:
  Resolution:	2560 x 1440 (QHD/WQHD - Wide Quad High Definition)
  UI Looks like:	2560 x 1440 @ 59 Hz
  Framebuffer Depth:	30-Bit Color (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Rotation:	Supported
  Automatically Adjust Brightness:	No
  Connection Type:	DisplayPort

这个问题能解决嘛，搜了下说可以改DVMT值，但找了半天没找到方法

**Comment by changly** [comment]
期待你的答案 @chanbaihai

**Comment by chanbaihai** [comment]
> 期待你的答案 @chanbaihai 

你去看下那个国外小哥的air efi库的pull request，我写了下过程怎么开4k，你试试看行不行

**Comment by changly** [comment]
> > 期待你的答案 @chanbaihai
> 
> 你去看下那个国外小哥的air efi库的pull request，我写了下过程怎么开4k，你试试看行不行

有联系方式吗？qq帮助一下？
