### ISSUE TITLE
请大佬支持下type-c转minidp-dp-显示器4k 60hz

### ISSUE THREAD

**Issue by han123580** [jasper-wan/Xiaomi-Air-i5-7200U#3]
犹如题目提示，请大佬支持下，目前我使用后外接4k只能被识别为2k,就算注入edid实际也只是2k的像素，特别模糊

**Comment by jasper-wan** [comment]
我手头并没有4k的显示器所以没办法测试

**Comment by zenghongqiang** [comment]
可以试试开启HIDIPI 我用的外接4K显示器 1080P HIDPI 能看，4K 60hz我在win系统下都不能实现 不知道为什么。用的是小米DP转接器 显示器用的也是DP接口

**Comment by jasper-wan** [comment]
有测试条件的可以参考<https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/117>

**Comment by jasper-wan** [comment]
合并入 #22
