### ISSUE TITLE
开机/睡眠唤醒无法自动识别外接屏

### ISSUE THREAD

**Issue by Yionr** [jasper-wan/Xiaomi-Air-i5-7200U#33]
OC引导+10.15.6
在关机状态下插上HDMI然后开机，外接屏不会自动点亮。需要开机之后拔掉HDMI重插才能识别到。
在外接屏正常工作的情况下待机唤醒后又无法识别到外接屏，需要再次重新拔插才能识别到。
外接屏没有点亮时候显示器设置中是这样的（再次之前已经正常插上HDMI）
<img width="586" alt="image" src="https://user-images.githubusercontent.com/30925732/93847100-928bea80-fcd8-11ea-891e-02abfc828602.png">

希望不是只有我一个人这样。。。

**Comment by misaka00251** [comment]
我也是这样,需要重新开关显示器.

**Comment by XiaoGuYa** [comment]
我在其他大佬的EFI里面找到的方法
首先在   config.plist   找到 <string>gfxrst=1 dart=0 vsmcgen=1 -lilubetaall</string>
然后修改为 <string>darkwake=0 gfxrst=1 igfxonln=1 igfxonlnfbs=0x010203</string>

**Comment by XiaoGuYa** [comment]
![image](https://user-images.githubusercontent.com/19884633/93858053-24eab900-fcee-11ea-9ee2-c4bb7a21bf86.png)

**Comment by ipatpat** [comment]
> 我在其他大佬的EFI里面找到的方法
> 首先在 config.plist 找到 gfxrst=1 dart=0 vsmcgen=1 -lilubetaall
> 然后修改为 darkwake=0 gfxrst=1 igfxonln=1 igfxonlnfbs=0x010203

It works! Thanks a lot!

**Comment by jasper-wan** [comment]
更新之后已经解决
