### ISSUE TITLE
大佬求解！

### ISSUE THREAD

**Issue by guchen2016** [jasper-wan/Xiaomi-Air-i5-7200U#7]
用你的EFI引导安装Mac os10.15后，开机发现USB扩展坞网线口接网线不能用了。
小白，不懂什么原因。求大佬指导

**Comment by jasper-wan** [comment]
重新安装对应的网卡驱动，这个不是EFI的问题

**Comment by Android-AwesomeRoy** [comment]
@guchen2016  请问你解决type-C口的网线驱动问题了嘛？

**Comment by guchen2016** [comment]
> @guchen2016 请问你解决type-C口的网线驱动问题了嘛？

没解决，我暂时换回10.14.6了，等等再说吧

**Comment by Android-AwesomeRoy** [comment]
@guchen2016  我不知道你买的哪家的扩展坞，绿联的网站里提供了驱动下载链接和配置方式。你也可以问一下你购买的产品的售后。
